import "@testing-library/jest-dom";
import { fromLocalStorage } from "../utils/localStorage";

test("return the correct array", () => {
  expect(fromLocalStorage("userList")).toEqual([
        { 
          id: "1",
          name: "Tom",
          role: "user",
          rights : [ 
            { id: 1,
              name: "createOrder",
              value: true,
            },
            { 
              id: 2,
              name: "deleteOrder",
              value: true,
            },
            { id: 3,
              name: "createCustomer",
              value: true,
            },
            { id: 4,
              name: "deleteCustomer",
              value: false,
            },
            { id: 5, 
              name: "createUser",
              value: false,
            },
            { id: 6,
              name: "deleteUser",
              value: false,
            },
          ],
          linked: ["1"],
        }, 
        { 
          id: "2",
          name: "Peter",
          role: "user",
          rights : [ 
            { id: 1,
              name: "createOrder",
              value: true,
            },
            { 
              id: 2,
              name: "deleteOrder",
              value: true,
            },
            { id: 3,
              name: "createCustomer",
              value: true,
            },
            { id: 4,
              name: "deleteCustomer",
              value: false,
            },
            { id: 5, 
              name: "createUser",
              value: false,
            },
            { id: 6,
              name: "deleteUser",
              value: false,
            },
          ],
          linked: ["1", "2"]
        },
        { 
          id: "3",
          name: "Anna",
          role: "user",
          rights : [ 
            { id: 1,
              name: "createOrder",
              value: true,
            },
            { 
              id: 2,
              name: "deleteOrder",
              value: true,
            },
            { id: 3,
              name: "createCustomer",
              value: true,
            },
            { id: 4,
              name: "deleteCustomer",
              value: false,
            },
            { id: 5, 
              name: "createUser",
              value: false,
            },
            { id: 6,
              name: "deleteUser",
              value: false,
            },
          ],
          linked: [],
        }, 
        { 
          id: "4",
          name: "Dieter",
          role: "admin",
          rights : [ 
            { id: 1,
              name: "createOrder",
              value: true,
            },
            { 
              id: 2,
              name: "deleteOrder",
              value: true,
            },
            { id: 3,
              name: "createCustomer",
              value: true,
            },
            { id: 4,
              name: "deleteCustomer",
              value: false,
            },
            { id: 5, 
              name: "createUser",
              value: false,
            },
            { id: 6,
              name: "deleteUser",
              value: false,
            },
          ],
          linked: [],
        }
      ]
  );
});
